### ISSUE TITLE
Monad Fetch is broken

### ISSUE THREAD

**Issue by Mr-Patty** [metrix-ai/potoki-core#6]
(>>=) does not work correctly.
Screening test:
```haskell
testCase "Fetch1 >>= Fetch2" $ do
  stVar1 <- newIORef [1]
  stVar2 <- newIORef [2,3]
  let fetch = Fe.list stVar1 >> Fe.list stVar2
  let prod = E.Produce $ pure fetch
  res <- C.produceAndConsume prod D.list
  assertEqual "" [2,3] res
```
Results:
> tests/Main.hs:82:
      expected: [2,3]
      but got: [2]

**Comment by effectfully** [comment]
Looking at

```haskell
instance Monad Fetch where
  return =
    pure
  (>>=) (Fetch leftIO) rightFetch =
    Fetch $ do
      leftFetching <- leftIO
      case leftFetching of
        Nothing -> return Nothing
        Just leftElement -> case rightFetch leftElement of
          Fetch rightIO -> rightIO
```

I see that the resulting `Fetch` calls `rightIO` exactly once on each `leftIO`. This is incorrect of course, as `rightIO` should be drained out before calling `leftIO` again.

It seems, `Fetch` is simply not a `Monad` and hence the `Monad` instance for `Produce` should be rewritten.

**Comment by nikita-volkov** [comment]
@effectfully Ready to do that?

**Comment by effectfully** [comment]
Yep.

**Comment by Mr-Patty** [comment]
Done. Removed the `Monad` instance for `Fetch` and rewrote the `Monad` instance for `Produce`.
